In [1]:
!pip install pandas scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix

In [9]:
from google.colab import files

uploaded = files.upload()

Saving .DS_Store to .DS_Store
Saving bank-full.csv to bank-full.csv

In [14]:
df = pd.read_csv("bank.csv")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'bank.csv'

In [15]:
import zipfile

with zipfile.ZipFile("bank-data.zip", 'r') as zip_ref:
    zip_ref.extractall("bank_data")

In [16]:
import os

os.listdir("bank_data")

['bank-data', '__MACOSX']

In [17]:
import os

os.listdir("bank_data/bank-data")

['.DS_Store', 'bank-full.csv']

In [18]:
import pandas as pd

df = pd.read_csv("bank_data/bank-data/bank.csv")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'bank_data/bank-data/bank.csv'

In [19]:
import pandas as pd

df = pd.read_csv("bank_data/bank-data/bank-full.csv")

df.head()

  age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0  58;"management";"married";"tertiary";"no";2143...
1  44;"technician";"single";"secondary";"no";29;"...
2  33;"entrepreneur";"married";"secondary";"no";2...
3  47;"blue-collar";"married";"unknown";"no";1506...
4  33;"unknown";"single";"unknown";"no";1;"no";"n...

In [20]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.select_dtypes(include='object').columns:

    df[col] = encoder.fit_transform(df[col])

df.head()

   age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0                                              42243
1                                              29482
2                                              11760
3                                              32327
4                                              13082

In [21]:
from sklearn.model_selection import train_test_split

X = df.drop("y", axis=1)

y = df["y"]

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    random_state=42

)

KeyError: "['y'] not found in axis"

In [22]:
import pandas as pd

df = pd.read_csv("bank_data/bank-data/bank-full.csv", sep=";")

df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [23]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [24]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in df.select_dtypes(include='object').columns:

    df[col] = encoder.fit_transform(df[col])

df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3,0
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3,0
2,33,2,1,1,0,2,1,1,2,5,8,76,1,-1,0,3,0
3,47,1,1,3,0,1506,1,0,2,5,8,92,1,-1,0,3,0
4,33,11,2,3,0,1,0,0,2,5,8,198,1,-1,0,3,0

In [25]:
from sklearn.model_selection import train_test_split

X = df.drop("y", axis=1)

y = df["y"]

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.2,
    random_state=42

)

In [26]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix

prediction = model.predict(X_test)

print("Accuracy =", accuracy_score(y_test, prediction))

print("Confusion Matrix")

print(confusion_matrix(y_test, prediction))

Accuracy = 0.885104500718788
Confusion Matrix
[[7785  167]
 [ 872  219]]